package com.alphaomegos.annasagenda.support

import com.alphaomegos.annasagenda.model.TravelBaseCountry
import com.alphaomegos.annasagenda.model.TravelContinent

/**
 * Reading the travel section's two shipped files (05.10), both generated by
 * tools/travel/make_travel_assets.py. Pure, so a test reads the very files
 * that ship; the phone skips a bad line rather than lose the rest.
 */
data class TravelBaseParse(val countries: List<TravelBaseCountry>, val problems: List<String>)

/** countries.tsv: "code<TAB>CONTINENT<TAB>English name"; "#" lines are comments. */
fun parseTravelBase(text: String): TravelBaseParse {
    val countries = mutableListOf<TravelBaseCountry>()
    val problems = mutableListOf<String>()
    val seen = HashSet<String>()
    text.lineSequence().forEachIndexed { i, raw ->
        val line = raw.trimEnd('\r')
        if (line.isBlank() || line.startsWith("#")) return@forEachIndexed
        val parts = line.split('\t')
        val code = parts.getOrNull(0)?.trim().orEmpty()
        val continent = TravelContinent.entries.firstOrNull { it.name == parts.getOrNull(1)?.trim() }
        val name = parts.getOrNull(2)?.trim().orEmpty()
        when {
            parts.size != 3 || !code.matches(Regex("[A-Z]{2}")) || continent == null || name.isEmpty() ->
                problems += "line ${i + 1}: $line"
            !seen.add(code) -> problems += "line ${i + 1}: $code again"
            else -> countries += TravelBaseCountry(code, continent, name)
        }
    }
    return TravelBaseParse(countries, problems)
}

/**
 * One country on the map: closed rings in grid units, filled even-odd (an
 * island is a ring, a lake inside is a ring too), or a single [dot] for a
 * country too small to draw; [bounds] is left, top, right, bottom.
 */
class TravelShape(val rings: List<IntArray>, val dot: Pair<Int, Int>?) {
    val bounds: IntArray = run {
        if (rings.isEmpty()) {
            val (x, y) = dot ?: (0 to 0)
            intArrayOf(x, y, x, y)
        } else {
            var l = Int.MAX_VALUE; var t = Int.MAX_VALUE; var r = Int.MIN_VALUE; var b = Int.MIN_VALUE
            rings.forEach { ring ->
                for (k in ring.indices step 2) {
                    l = minOf(l, ring[k]); r = maxOf(r, ring[k])
                    t = minOf(t, ring[k + 1]); b = maxOf(b, ring[k + 1])
                }
            }
            intArrayOf(l, t, r, b)
        }
    }

    /** Whether ([x], [y]) is inside, by the even-odd rule the map is filled with. */
    fun contains(x: Float, y: Float): Boolean {
        if (x < bounds[0] || x > bounds[2] || y < bounds[1] || y > bounds[3]) return false
        var inside = false
        rings.forEach { ring ->
            val n = ring.size / 2
            var j = n - 1
            for (i in 0 until n) {
                val xi = ring[2 * i].toFloat(); val yi = ring[2 * i + 1].toFloat()
                val xj = ring[2 * j].toFloat(); val yj = ring[2 * j + 1].toFloat()
                if ((yi > y) != (yj > y) && x < (xj - xi) * (y - yi) / (yj - yi) + xi) inside = !inside
                j = i
            }
        }
        return inside
    }
}

/** The world map: its grid, and every country's shape by code. */
class TravelWorldMap(val width: Int, val height: Int, val shapes: Map<String, TravelShape>) {

    /**
     * The country at ([x], [y]) on the grid, or null for the sea. A dot is
     * hit within [dotRadius] grid units; dots win over outlines, being the
     * small things one aims at.
     */
    fun countryAt(x: Float, y: Float, dotRadius: Float): String? {
        shapes.entries
            .filter { it.value.dot != null }
            .minByOrNull { (_, s) -> val (dx, dy) = s.dot!!; (dx - x) * (dx - x) + (dy - y) * (dy - y) }
            ?.let { (code, s) ->
                val (dx, dy) = s.dot!!
                if ((dx - x) * (dx - x) + (dy - y) * (dy - y) <= dotRadius * dotRadius) return code
            }
        return shapes.entries.firstOrNull { it.value.rings.isNotEmpty() && it.value.contains(x, y) }?.key
    }
}

data class TravelMapParse(val map: TravelWorldMap, val problems: List<String>)

/**
 * world_map.txt: "size W H", then "CODE<TAB>ring;ring" with each ring x,y and
 * then dx,dy steps, or "CODE<TAB>@x,y" for a dot. Rings come back with
 * absolute coordinates.
 */
fun parseTravelWorldMap(text: String): TravelMapParse {
    var width = 0
    var height = 0
    val shapes = LinkedHashMap<String, TravelShape>()
    val problems = mutableListOf<String>()
    text.lineSequence().forEachIndexed { i, raw ->
        val line = raw.trimEnd('\r')
        if (line.isBlank() || line.startsWith("#")) return@forEachIndexed
        if (line.startsWith("size ")) {
            val p = line.split(' ')
            width = p.getOrNull(1)?.toIntOrNull() ?: 0
            height = p.getOrNull(2)?.toIntOrNull() ?: 0
            return@forEachIndexed
        }
        val code = line.substringBefore('\t')
        val data = line.substringAfter('\t', "")
        val shape = runCatching {
            if (data.startsWith("@")) {
                val (x, y) = data.drop(1).split(',').map { it.trim().toInt() }
                TravelShape(emptyList(), x to y)
            } else {
                TravelShape(data.split(';').map { ring -> absoluteRing(ring) }, null)
            }
        }.getOrNull()
        when {
            !code.matches(Regex("[A-Z]{2}")) || shape == null -> problems += "line ${i + 1}: ${line.take(40)}"
            code in shapes -> problems += "line ${i + 1}: $code again"
            else -> shapes[code] = shape
        }
    }
    if (width <= 0 || height <= 0) problems += "no size line"
    return TravelMapParse(TravelWorldMap(width, height, shapes), problems)
}

private fun absoluteRing(text: String): IntArray {
    val nums = text.split(',').map { it.trim().toInt() }
    require(nums.size >= 6 && nums.size % 2 == 0)
    val out = IntArray(nums.size)
    var x = 0
    var y = 0
    for (k in nums.indices step 2) {
        if (k == 0) {
            x = nums[0]; y = nums[1]
        } else {
            x += nums[k]; y += nums[k + 1]
        }
        out[k] = x; out[k + 1] = y
    }
    return out
}
